version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=5000
      - JWT_SECRET=${JWT_SECRET:-smartsprint_secret}
      - JWT_EXPIRY=${JWT_EXPIRY:-7d}
      - DATABASE_PATH=./database/smartsprint.db
    command: sh -c "npm run init-db && npm start"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: smartsprint_network 